In [4]:
import pandas as pd
import requests
from tqdm import tqdm
import geopandas

In [115]:
#인풋데이터 불러오기
input_data = pd.read_csv('./df2.csv')
input_data = input_data.reset_index(drop=True)

In [117]:
#위도(lat),경도(lng)불러오는 함수
def get_lat_lng(address):
    #카카오톡 api 불러오기
    url = f'https://dapi.kakao.com/v2/local/search/address.json?query={address}'
    headers = {
    ## 여러분의 카카오 API의 REST API키를 아래 예시와 같이 입력해주세요
    ## "Authorization": "KakaoAK REST API키 입력 gogo"}
    "Authorization": "KakaoAK 1358366e6234ef1b494f623fa9b7fd03"}
    response = requests.get(url, headers = headers).json()
    try : 
        #위경도
        Lat = response.get('documents')[0].get('y')
        Lng = response.get('documents')[0].get('x')
    
    except : 
        Lat = 'error'
        Lng = 'error'

    return Lat, Lng

In [118]:
df = input_data

In [119]:
df_test = df.iloc[:100,:]

In [122]:
df_test['Lat_Lng'] = df_test.지번주소.apply(lambda x : get_lat_lng(x))

/var/folders/cb/0cgtts7x7ps8zly4sl8xwntc0000gn/T/ipykernel_16417/1901763945.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['Lat_Lng'] = df_test.지번주소.apply(lambda x : get_lat_lng(x))

In [123]:
df_test

,시,구,동,번지,지번주소,본번,부번,단지명,전용면적(㎡),계약년월,...,거래금액(만원),층,건축년수,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,기준 금리,Lat_Lng
0,서울특별시,관악구,봉천동,870-1,서울특별시 관악구 봉천동 870-1,870,1,해주타워,22.00,202005,...,"10,500",6,24.0,2000.0,봉천로 466,NaN,-,-,0.75,"(37.4819710829378, 126.951615607239)"
1,서울특별시,관악구,신림동,1638-1,서울특별시 관악구 신림동 1638-1,1638,1,삼모 더 프라임 타워,23.89,202005,...,"16,150",11,13.0,2011.0,신원로 35,NaN,-,-,0.75,"(37.4822394616082, 126.928918636076)"
2,서울특별시,관악구,신림동,1638-1,서울특별시 관악구 신림동 1638-1,1638,1,삼모 더 프라임 타워,23.89,202005,...,"16,150",11,13.0,2011.0,신원로 35,20200521.0,-,-,0.75,"(37.4822394616082, 126.928918636076)"
3,서울특별시,관악구,신림동,1421-1,서울특별시 관악구 신림동 1421-1,1421,1,신림큐브,16.32,202005,...,"11,200",3,9.0,2015.0,신림로66길 42,NaN,-,-,0.75,"(37.4855860298558, 126.932054229593)"
4,서울특별시,구로구,구로동,187-3,서울특별시 구로구 구로동 187-3,187,3,예성유토피아(187-3),40.16,202005,...,"20,000",3,19.0,2005.0,도림천로 448,NaN,-,-,0.75,"(37.485683268026, 126.899053661374)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,서울특별시,서초구,방배동,754-1,서울특별시 서초구 방배동 754-1,754,1,롯데캐슬헤론,38.54,202005,...,"35,500",4,18.0,2006.0,동광로1길 112,NaN,-,-,0.75,"(37.4969407304439, 126.984306628076)"
96,서울특별시,송파구,문정동,624,서울특별시 송파구 문정동 624,624,0,송파 아이파크,25.87,202005,...,"22,400",8,9.0,2015.0,법원로 55,NaN,-,-,0.75,"(37.4798682885767, 127.12174819551)"
97,서울특별시,송파구,잠실동,176-2,서울특별시 송파구 잠실동 176-2,176,2,잠실동 렉스빌2차,47.24,202005,...,"41,600",16,11.0,2013.0,백제고분로7길 3-10,NaN,-,-,0.75,"(37.5109131735157, 127.079303306557)"
98,서울특별시,송파구,잠실동,194,서울특별시 송파구 잠실동 194,194,0,잠실아이파크,24.42,202005,...,"26,600",8,11.0,2013.0,올림픽로8길 20,20200512.0,-,-,0.75,"(37.5100559145811, 127.080035657776)"
99,서울특별시,송파구,잠실동,194,서울특별시 송파구 잠실동 194,194,0,잠실아이파크,24.42,202005,...,"26,600",8,11.0,2013.0,올림픽로8길 20,NaN,-,-,0.75,"(37.5100559145811, 127.080035657776)"

In [124]:
df['Lat_Lng'] = df.지번주소.apply(lambda x : get_lat_lng(x))

In [128]:
df.to_csv('./output.csv', index=False, encoding='utf-8-sig')

In [110]:
count = 0
for i in range(len(df_test)):
    if df_test['Lat_Lng'][i] == ('error', 'error'):
        count += 1
print(count)

72

In [112]:
address = '서울특별시 영등포구 신길동 324-53'

url = f'https://dapi.kakao.com/v2/local/search/address.json?query={address}'
headers = {
## 여러분의 카카오 API의 REST API키를 아래 예시와 같이 입력해주세요
## "Authorization": "KakaoAK REST API키 입력 gogo"}
"Authorization": "KakaoAK 1358366e6234ef1b494f623fa9b7fd03"}
response = requests.get(url, headers = headers).json()

response

In [113]:
response

{'documents': [],
 'meta': {'is_end': True, 'pageable_count': 0, 'total_count': 0}}